export const colorPalette = [
  { color: "#FFD1D1", value: "Light Red" },
  { color: "#FFE3C1", value: "Peach" },
  { color: "#FFF0C1", value: "Soft Yellow" },
  { color: "#EBF7C1", value: "Light Lime" },
  { color: "#C1F4C1", value: "Mint Green" },
  { color: "#C1F0E4", value: "Light Aqua" },
  { color: "#C1E7F7", value: "Sky Blue" },
  { color: "#C1D1FF", value: "Light Lavender" },
  { color: "#E1C1FF", value: "Lilac" },

  { color: "#FFA3A3", value: "Pinkish Red" },
  { color: "#FFC69B", value: "Apricot" },
  { color: "#FFE39B", value: "Butter Yellow" },
  { color: "#DFF39B", value: "Chartreuse" },
  { color: "#9BF1A3", value: "Light Green" },
  { color: "#9BECD9", value: "Teal" },
  { color: "#9BE2F3", value: "Light Cyan" },
  { color: "#9BA3FF", value: "Periwinkle" },
  { color: "#CD9BFF", value: "Orchid Purple" },

  { color: "#FF7F7F", value: "Soft Red" },
  { color: "#FFAF70", value: "Coral" },
  { color: "#FFDB70", value: "Golden Yellow" },
  { color: "#D1EC70", value: "Yellow-Green" },
  { color: "#70E8A3", value: "Seafoam Green" },
  { color: "#70E0D6", value: "Light Turquoise" },
  { color: "#70D6E8", value: "Soft Blue" },
  { color: "#707AFF", value: "Deep Lavender" },
  { color: "#B370FF", value: "Violet" },

  { color: "#FF6666", value: "Red" },
  { color: "#FF9966", value: "Orange" },
  { color: "#FFCC66", value: "Yellow-Orange" },
  { color: "#CCE366", value: "Lime Green" },
  { color: "#66DAA3", value: "Bright Mint" },
  { color: "#66CFCF", value: "Turquoise" },
  { color: "#66CCE3", value: "Sky Turquoise" },
  { color: "#6673FF", value: "Indigo" },
  { color: "#A366FF", value: "Purple" },

  { color: "#FF4D4D", value: "Crimson" },
  { color: "#FF804D", value: "Sunset Orange" },
  { color: "#FFB84D", value: "Amber" },
  { color: "#B3D94D", value: "Greenish Yellow" },
  { color: "#4DD490", value: "Emerald Green" },
  { color: "#4DBFBF", value: "Aqua Green" },
  { color: "#4DB8D1", value: "Azure" },
  { color: "#4D6DFF", value: "Blue" },
  { color: "#934DFF", value: "Royal Purple" },

  { color: "#FF3333", value: "Bright Red" },
  { color: "#FF6633", value: "Burnt Orange" },
  { color: "#FFA333", value: "Goldenrod" },
  { color: "#99CF33", value: "Light Olive" },
  { color: "#33B97D", value: "Jade Green" },
  { color: "#33A8A8", value: "Cool Teal" },
  { color: "#33A8C4", value: "Deep Sky Blue" },
  { color: "#334FFF", value: "Electric Blue" },
  { color: "#8033FF", value: "Deep Violet" },

  { color: "#CC0000", value: "Dark Red" },
  { color: "#CC5200", value: "Dark Orange" },
  { color: "#CC9900", value: "Gold" },
  { color: "#7FBF00", value: "Apple Green" },
  { color: "#00A664", value: "Forest Green" },
  { color: "#008787", value: "Dark Cyan" },
  { color: "#007399", value: "Steel Blue" },
  { color: "#0033CC", value: "Royal Blue" },
  { color: "#6600CC", value: "Dark Purple" },

  { color: "#990000", value: "Maroon" },
  { color: "#993D00", value: "Rust" },
  { color: "#997300", value: "Bronze" },
  { color: "#668F00", value: "Olive Green" },
  { color: "#008757", value: "Pine Green" },
  { color: "#006D6D", value: "Teal Green" },
  { color: "#005D7F", value: "Slate Blue" },
  { color: "#002699", value: "Navy Blue" },
  { color: "#4D0099", value: "Plum" },

  { color: "#660000", value: "Dark Maroon" },
  { color: "#662400", value: "Mahogany" },
  { color: "#665200", value: "Mustard" },
  { color: "#4D6600", value: "Army Green" },
  { color: "#00663D", value: "Bottle Green" },
  { color: "#004D4D", value: "Dark Aqua" },
  { color: "#004D66", value: "Ocean Blue" },
  { color: "#001A66", value: "Midnight Blue" },
  { color: "#330066", value: "Deep Plum" },

  { color: "#333333", value: "Charcoal" },
  { color: "#4D4D4D", value: "Dim Gray" },
  { color: "#666666", value: "Gray" },
  { color: "#808080", value: "Cool Gray" },
  { color: "#999999", value: "Light Gray" },
  { color: "#B3B3B3", value: "Silver" },
  { color: "#CCCCCC", value: "Platinum" },
  { color: "#E6E6E6", value: "Pearl" },
  { color: "#FFFFFF", value: "White" },
];
