export const ROUTES = {
  ADMIN: {
    index: "/admin",
    users: "/admin/users",
    products: "/admin/products",
    productsInner: "/admin/products/:productId",
    detailProducts: "/admin/detail-prodacts",
    addProductsDefault: "/admin/add-products-default",
    addProduct: "/admin/add-product",
    addPrice: "/admin/add-price",
    aboutProducts: "/admin/about-products",
    productTable: "/admin/:productId/product-table",
    productInner: "/admin/:productId",
    adminRewiv: "/admin/review-raiting",
    adminDelivery: "/admin/delivery",
  },
  USER: {
    index: "/",
    profile: "user/profile",
    orderHistory: "user/account-order-history",
    compare: "user/compare",
    aboutStore: "/user/about-store",
    delivery: "/user/delivery",
    faq: "/user/faq",
    contacts: "/user/contacts",
    productCard: "/user/product/:productId",
    favourit: "/user/favourit",
    productCatalog: "/user/catalog/:category",
    basket: "/user/basket",
    accountFavourites: "user/account-favourites",
  },
  GUEST: { index: "/", signIn: "sign-in", signUp: "sign-up" },
};
